-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 18, 2020 at 01:23 PM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `theswordsnestdb`
--
CREATE DATABASE IF NOT EXISTS `theswordsnestdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `theswordsnestdb`;

-- --------------------------------------------------------

--
-- Table structure for table `items`
--

CREATE TABLE `items` (
  `Id` int(11) NOT NULL,
  `NameOfTheBook` varchar(255) NOT NULL,
  `Author` varchar(255) NOT NULL,
  `BookCover` varchar(255) NOT NULL,
  `Price` float NOT NULL,
  `BookDescription` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `items`
--

INSERT INTO `items` (`Id`, `NameOfTheBook`, `Author`, `BookCover`, `Price`, `BookDescription`) VALUES
(1, 'The Fellowship of the Ring', 'J.R.R. Tolkien', '.\\Photos\\TLOTR1.jpg', 12.99, '(The Lord Of The Rings #1) One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkeness bind them. <br><br>In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, The Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit. <br><br>In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.'),
(2, 'The Two Towers', 'J.R.R. Tolkien', '.\\Photos\\TLOTR2.jpg', 14.99, '(The Lord Of The Rings #2) The Fellowship was scattered. Some were bracing hopelessly for war against the ancient evil of Sauron. Some were contending with the treachery of the wizard Saruman. Only Frodo and Sam were left to take the accursed Ring of Power to be destroyed in Mordor–the dark Kingdom where Sauron was supreme. Their guide was Gollum, deceitful and lust-filled, slave to the corruption of the Ring. Thus continues the magnificent, bestselling tale of adventure begun in The Fellowship of the Ring, which reaches its soul-stirring climax in The Return of the King.'),
(3, 'The Return Of The King', 'J.R.R. Tolkien', '.\\Photos\\TLOTR3.jpg', 12.99, '(The Lord Of The Rings #3) The Companions of the Ring have become involved in separate adventures as the quest continues. Aragorn, revealed as the hidden heir of the ancient Kings of the West, joined with the Riders of Rohan against the forces of Isengard, and took part in the desperate victory of the Hornburg. Merry and Pippin, captured by Orcs, escaped into Fangorn Forest and there encountered the Ents. Gandalf returned, miraculously, and defeated the evil wizard, Saruman. Meanwhile, Sam and Frodo progressed towards Mordor to destroy the Ring, accompanied by SmEagol--Gollum, still obsessed by his \'precious\'. After a battle with the giant spider, Shelob, Sam left his master for dead; but Frodo is still alive--in the hands of the Orcs. And all the time the armies of the Dark Lord are massing. J.R.R. Tolkien\'s great work of imaginative fiction has been labeled both a heroic romance and a classic fantasy fiction. By turns comic and homely, epic and diabolic, the narrative moves through countless changes of scene and character in an imaginary world which is totally convincing in its detail.'),
(4, 'The Hobbit', 'J.R.R. Tolkien', '.\\Photos\\TheHobbit.jpg', 10.99, 'In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort. Written for J.R.R. Tolkien’s own children, The Hobbit met with instant critical acclaim when it was first published in 1937. Now recognized as a timeless classic, this introduction to the hobbit Bilbo Baggins, the wizard Gandalf, Gollum, and the spectacular world of Middle-earth recounts of the adventures of a reluctant hero, a powerful and dangerous ring, and the cruel dragon Smaug the Magnificent.'),
(5, 'The Silmarillion', 'J.R.R. Tolkien', '.\\Photos\\TheSilmarillion.jpg', 14.99, 'The story of the creation of the world and of the the First Age, this is the ancient drama to which the characters in THE LORD OF THE RINGS look back and in whose events some of them, such as Elrond and Galadriel, took part. The three Silmarils were jewels created by Feanor, most gifted of the Elves. Within them was imprisoned the Light of the Two Trees of Valinor before the Trees themselves were destroyed by Morgoth, the first Dark Lord. Thereafter, the unsullied Light of Valinor lived on only in the Silmarils, but they were seized by Morgoth and set in his crown, which was guarded in the impenetrable fortress of Angband in the north of Middle-earth. THE SILMARILLION is the history of the rebellion of Feanor and his kindred against the gods, their exile from Valinor and return to Middle-earth, and their war, hopeless despite all their heroism, against the great Enemy.'),
(6, 'The Way Of Kings', 'Brandon Sanderson', '.\\Photos\\TheWayOfKings.jpg', 17.99, '(The Stormlight Archive #1) I long for the days before the Last Desolation. <br><br>The age before the Heralds abandoned us and the Knights Radiant turned against us. A time when there was still magic in the world and honor in the hearts of men. <br><br>The world became ours, and yet we lost it. Victory proved to be the greatest test of all. Or was that victory illusory? Did our enemies come to recognize that the harder they fought, the fiercer our resistance? Fire and hammer will forge steel into a weapon, but if you abandon your sword, it eventually rusts away. <br><br>There are four whom we watch. The first is the surgeon, forced to forsake healing to fight in the most brutal war of our time. The second is the assassin, a murderer who weeps as he kills. The third is the liar, a young woman who wears a scholar\'s mantle over the heart of a thief. The last is the prince, a warlord whose eyes have opened to the ancient past as his thirst for battle wanes. <br><br>The world can change. Surgebinding and Shardwielding can return; the magics of ancient days become ours again. These four people are key. <br><br>One of them may redeem us. And one of them will destroy us.'),
(7, 'Words Of Radiance', 'Brandon Sanderson', '.\\Photos\\WordsOfRadiance.jpg', 16.99, '(The Stormlight Archive #2) Expected by his enemies to die the miserable death of a military slave, Kaladin survived to be given command of the royal bodyguards, a controversial first for a low-status \"darkeyes.\" Now he must protect the king and Dalinar from every common peril as well as the distinctly uncommon threat of the Assassin, all while secretly struggling to master remarkable new powers that are somehow linked to his honorspren, Syl. <br><br>The Assassin, Szeth, is active again, murdering rulers all over the world of Roshar, using his baffling powers to thwart every bodyguard and elude all pursuers. Among his prime targets is Highprince Dalinar, widely considered the power behind the Alethi throne. His leading role in the war would seem reason enough, but the Assassin\'s master has much deeper motives. <br><br>Brilliant but troubled Shallan strives along a parallel path. Despite being broken in ways she refuses to acknowledge, she bears a terrible burden: to somehow prevent the return of the legendary Voidbringers and the civilization-ending Desolation that will follow. The secrets she needs can be found at the Shattered Plains, but just arriving there proves more difficult than she could have imagined. <br><br>Meanwhile, at the heart of the Shattered Plains, the Parshendi are making an epochal decision. Hard pressed by years of Alethi attacks, their numbers ever shrinking, they are convinced by their war leader, Eshonai, to risk everything on a desperate gamble with the very supernatural forces they once fled. The possible consequences for Parshendi and humans alike, indeed, for Roshar itself, are as dangerous as they are incalculable.'),
(8, 'Oathbringer', 'Brandon Sanderson', '.\\Photos\\Oathbringer.jpg', 12.99, '(The Stormlight Archive #3) Dalinar Kholin\'s Alethi armies won a fleeting victory at a terrible cost: The enemy Parshendi summoned the violent Everstorm, which now sweeps the world with destruction, and in its passing awakens the once peaceful and subservient parshmen to the horror of their millennia-long enslavement by humans. While on a desperate flight to warn his family of the threat, Kaladin Stormblessed must come to grips with the fact that the newly kindled anger of the parshmen may be wholly justified. <br><br>Nestled in the mountains high above the storms, in the tower city of Urithiru, Shallan Davar investigates the wonders of the ancient stronghold of the Knights Radiant and unearths dark secrets lurking in its depths. And Dalinar realizes that his holy mission to unite his homeland of Alethkar was too narrow in scope. Unless all the nations of Roshar can put aside Dalinar\'s blood-soaked past and stand together--and unless Dalinar himself can confront that past--even the restoration of the Knights Radiant will not prevent the end of civilization.'),
(9, 'Rhythm Of War', 'Brandon Sanderson', '.\\Photos\\RhythmOfWar.jpg', 10.99, '(The Stormlight Archive #4) After forming a coalition of human resistance against the enemy invasion, Dalinar Kholin and his Knights Radiant have spent a year fighting a protracted, brutal war. Neither side has gained an advantage. <br><br>Now, as new technological discoveries begin to change the face of the war, the enemy prepares a bold and dangerous operation. The arms race that follows will challenge the very core of the Radiant ideals, and potentially reveal the secrets of the ancient tower that was once the heart of their strength.'),
(10, 'Edgedancer', 'Brandon Sanderson', '.\\Photos\\Edgedancer.jpg', 8.99, '(The Stormlight Archive #2.5) Three years ago, Lift asked a goddess to stop her from growing older--a wish she believed was granted. Now, in Edgedancer, the barely teenage nascent Knight Radiant finds that time stands still for no one. Although the young Azish emperor granted her safe haven from an executioner she knows only as Darkness, court life is suffocating the free-spirited Lift, who can\'t help heading to Yeddaw when she hears the relentless Darkness is there hunting people like her with budding powers. The downtrodden in Yeddaw have no champion, and Lift knows she must seize this awesome responsibility.'),
(11, 'The Name Of The Wind', 'Patrick Rothfuss', '.\\Photos\\TheNameOfTheWind.jpg', 12.99, '(The Kingkiller Chronicle #1) Told in Kvothe\'s own voice, this is the tale of the magically gifted young man who grows to be the most notorious wizard his world has ever seen. <br><br>The intimate narrative of his childhood in a troupe of traveling players, his years spent as a near-feral orphan in a crime-ridden city, his daringly brazen yet successful bid to enter a legendary school of magic, and his life as a fugitive after the murder of a king form a gripping coming-of-age story unrivaled in recent literature.'),
(12, 'The Wise Man\'s Fear', 'Patrick Rothfuss', '.\\Photos\\TheWiseMansFear.jpg', 11.99, '(The Kingkiller Chronicle #2) “There are three things all wise men fear: the sea in storm, a night with no moon, and the anger of a gentle man.” <br><br>My name is Kvothe. <br>I have stolen princesses back from sleeping barrow kings. I burned down the town of Trebon. I have spent the night with Felurian and left with both my sanity and my life. I was expelled from the University at a younger age than most people are allowed in. I tread paths by moonlight that others fear to speak of during day. I have talked to Gods, loved women, and written songs that make the minstrels weep. <br>You may have heard of me. <br><br>So begins the tale of a hero told from his own point of view — a story unequaled in fantasy literature. Now in The Wise Man\'s Fear, an escalating rivalry with a powerful member of the nobility forces Kvothe to leave the University and seek his fortune abroad. Adrift, penniless, and alone, he travels to Vintas, where he quickly becomes entangled in the politics of courtly society. While attempting to curry favor with a powerful noble, Kvothe uncovers an assassination attempt, comes into conflict with a rival arcanist, and leads a group of mercenaries into the wild, in an attempt to solve the mystery of who (or what) is waylaying travelers on the King\'s Road. <br><br>All the while, Kvothe searches for answers, attempting to uncover the truth about the mysterious Amyr, the Chandrian, and the death of his parents. Along the way, Kvothe is put on trial by the legendary Adem mercenaries, is forced to reclaim the honor of the Edema Ruh, and travels into the Fae realm. There he meets Felurian, the faerie woman no man can resist, and who no man has ever survived ... until Kvothe. <br><br>In The Wise Man\'s Fear, Kvothe takes his first steps on the path of the hero and learns how difficult life can be when a man becomes a legend in his own time.'),
(13, 'The Blade Itself', 'Joe Abercrombie', '.\\Photos\\TheBladeItself.jpg', 10.99, '(The First Law #1) Logen Ninefingers, infamous barbarian, has finally run out of luck. Caught in one feud too many, he’s on the verge of becoming a dead barbarian – leaving nothing behind him but bad songs, dead friends, and a lot of happy enemies. <br><br>Nobleman Captain Jezal dan Luthar, dashing officer, and paragon of selfishness, has nothing more dangerous in mind than fleecing his friends at cards and dreaming of glory in the fencing circle. But war is brewing, and on the battlefields of the frozen North they fight by altogether bloodier rules.<br><br>Inquisitor Glokta, cripple turned torturer, would like nothing better than to see Jezal come home in a box. But then Glokta hates everyone: cutting treason out of the Union one confession at a time leaves little room for friendship. His latest trail of corpses may lead him right to the rotten heart of government, if he can stay alive long enough to follow it. <br><br>Enter the wizard, Bayaz. A bald old man with a terrible temper and a pathetic assistant, he could be the First of the Magi, he could be a spectacular fraud, but whatever he is, he\'s about to make the lives of Logen, Jezal, and Glokta a whole lot more difficult. <br><br>Murderous conspiracies rise to the surface, old scores are ready to be settled, and the line between hero and villain is sharp enough to draw blood.'),
(14, 'Before They Are Hanged', 'Joe Abercrombie', '.\\Photos\\BeforeTheyAreHanged.jpg', 14.99, '(The First Law #2) Superior Glokta has a problem. How do you defend a city surrounded by enemies and riddled with traitors, when your allies can by no means be trusted, and your predecessor vanished without a trace? It’s enough to make a torturer want to run – if he could even walk without a stick.<br><br>Northmen have spilled over the border of Angland and are spreading fire and death across the frozen country. Crown Prince Ladisla is poised to drive them back and win undying glory. There is only one problem – he commands the worst-armed, worst-trained, worst-led army in the world.<br><br>And Bayaz, the First of the Magi, is leading a party of bold adventurers on a perilous mission through the ruins of the past. The most hated woman in the South, the most feared man in the North, and the most selfish boy in the Union make a strange alliance, but a deadly one. They might even stand a chance of saving mankind from the Eaters. If they didn’t hate each other quite so much.<br><br>Ancient secrets will be uncovered. Bloody battles will be won and lost. Bitter enemies will be forgiven – but not before they are hanged.'),
(15, 'Last Argument Of Kings', 'Joe Abercrombie', '.\\Photos\\LastArgumentOfKings.jpg', 12.99, '(The First Law #3) The end is coming. Logen Ninefingers might only have one more fight in him but it\'s going to be a big one. Battle rages across the North, the King of the Northmen still stands firm, and there\'s only one man who can stop him. His oldest friend, and his oldest enemy. It\'s past time for the Bloody-Nine to come home. <br><br>With too many masters and too little time, Superior Glokta is fighting a different kind of war. A secret struggle in which no one is safe, and no one can be trusted. His days with a sword are far behind him. It\'s a good thing blackmail, threats and torture still work well enough.<br><br>Jezal dan Luthar has decided that winning glory is far too painful, and turned his back on soldiering for a simple life with the woman he loves. But love can be painful too, and glory has a nasty habit of creeping up on a man when he least expects it.<br><br>While the King of the Union lies on his deathbead, the peasants revolt and the nobles scramble to steal his crown. No one believes that the shadow of war is falling across the very heart of the Union. The First of the Magi has a plan to save the world, as he always does. But there are risks. There is no risk more terrible, after all, than to break the First Law...');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `items`
--
ALTER TABLE `items`
  ADD PRIMARY KEY (`Id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `items`
--
ALTER TABLE `items`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
